name: Deploy UI Application

on:
  push:
    branches:
      - main
      
jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH into EC2 and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_NAME }}
          username: ${{ secrets.USER_NAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            # Navigate to the directory containing the UI application
            cd /home/ubuntu/Ecom-website-bootstrap-javascaript
            
            # Pull latest changes from the repository and rebase local changes
            git pull origin master --rebase
            
            # Copy the updated files to the web server directory
            sudo cp -r * /var/www/html
            
            # Stop the nginx web server to apply changes
            sudo systemctl stop nginx.service
            
            # Reload the systemd daemon to ensure nginx picks up changes
            sudo systemctl daemon-reload
            
            # Restart the nginx service to apply changes
            sudo systemctl restart nginx.service
            
            # Check the status of the nginx service to verify successful restart
            sudo systemctl status nginx.service
